{% set name = "jupyterlab-transient-display-data" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/t/transient-display-data/transient-display-data-{{ version }}.tar.gz
  sha256: a5692bb7bbda0cf77ddffe802a4b5e101f7458dd909bfe5c799fa4525c5de2b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - nodejs
  host:
    - jupyter-packaging
    - pip
    - python >=3.5
  run:
    - jupyterlab >=3.0.0
    - nodejs
    - python >=3.6

test:
  commands:
    - jupyter labextension list
    - jupyter lab build
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - grep "transient-display-data.*enabled.*OK" labextensions  # [unix]


about:
  home: https://github.com/vatlab/transient-display-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension for the rendering transient-display-data messages
  dev_url: https://github.com/vatlab/transient-display-data

extra:
  recipe-maintainers:
    - BoPeng
    - izahn
