travis:
  secure:
    BINSTAR_TOKEN: hRageJulTD04byBaI/D/1sal3p4W5Cx0zZqOwIIlgke5FPRnI9Gnt/W87admg9NErdfBG0tUIbSsvfpL7y/Dhs4tmuGb5SqltKM4Fx7eHQgLH6U3jDf4TZMS4hvnFlWz49BDEl82SVPJ0sTW2SlnuzJ/BOzMKziYlS8guJfgSWqsod3q2YC38NiLz0WutUTMfjD0TcpqMA8wTc9/G8QKkMIZoS0ZCRgD/KrBZocxhZ/L/x8ISl8wctQIzKH1XAtWIXefICUn8WhnpVcdcDvauT/Uc/036plT6h4Wp94Hy0lOb/7oGA23zBP9adLB9xPjmQrnpkjDG86x5LRartFgJB340UHheliNu6424rZYHGhZfrWyUF2gT2rGgHhrjmnnwyt3VHEFQf/AW5ylwXHVUXjPQnAhnGEFc4gWxJF15BzL53QRILVDvuywh5sFxowCz5LVHRlLhNV/a7C/GBaFYxdiF9FDi9bgVYY59J/GbWA9XY6DcxVgYX/7mp7C6poMgKmcgpsSBFnrgeaUnAPmj3xckaQ0t28AwoS0SapEn8EcldgDYLANcqizsofjp+ehdxwpVEKRP7GlN3vL4hGjkVRS4GZHts2JJIMkQhcCwdnESDtHB3yHSb8xALdzx77ttq6sJFK/e2cbj9kviqEdtbwAxblyu4bxcoP8/wKNTSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
