travis:
  secure:
    BINSTAR_TOKEN: CtezvdH9waDHUkAV8EfdbkdPy1XgreBj5w+uBbS59oc0/pdZGsXFPgV3yxqUDakYoj0vdz0jUfEzhMIufo+633GCvmXt9uX3g1QAijgcSoAHHAuPIZv7p23z7eV1y+WKRAYscGOXHyGLuQ5xijB0aVLc5ffb5AVRbAaTk/hqTBX5+miDog0pr+tL0VkRBA8mW6KQ7QOgVc2x6nva2pCvikZ53w00Sxf5cuDleKXMZOymZjBge0w0VztslnL5GLvjkUZjNXjBGAQ6b5QbR133t4YhLUgVkvAmQdt9tw1d0raLvB9i7uvfvIasHcf2yFmBvLzmyA7eY2VXOqBV1039ALSU4Qs6Gu75W717IrDe4HscEBZTGOESBNHnn35ELalo//oEXUNjL9iym/8Lhs5OHVguHPcmUxuQiGXQZzf3oMUKdADw4AElJgqrXk8ZXHPQSaO1Hc74+n+gX93Az8oSpcmjVVV7xA/TADEHietWOOMulk9syMRk/UvTUIvQoKn1YnExCIufcZ407zukWecFqSnNKCdpRoV4fEZkYhr7tW7AVFXfxvPTV2bo0M9WQWvM2+zigtVTizdlA1yT+fRpLd6pXnrZEZibKr9jq/sQPZuL+EulWZ6IhNb3VOBWr7rBqlrWRNc5y4t/35Ff+5pnZpsDLOzTQmNYTnySlzgD4xw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
